### ISSUE TITLE
Close messages after unmuting members.

### ISSUE THREAD

**Issue by MaxWizard1** [viperadnan-git/force-subscribe-telegram-bot#1]
When People click on UnMute after Subscribe Channel,, 
Mention message not Closed after click on UnMute. Please add this feature,

**Comment by viperadnan-git** [comment]
On next update.

**Comment by viperadnan-git** [comment]
Done. See [805bd0d](https://github.com/viperadnan-git/force-subscribe-telegram-bot/commit/805bd0d60adece22ab0bc51eeabf782e2194033e)
